### ISSUE TITLE
Baidu can't be accessed in Europe

### ISSUE THREAD

**Issue by morsingher** [WanquanF/NeuralPoints#11]
Hi, I'm trying to download your dataset but it is impossible to create a Baidu account from Europe, even with all the tricks you can find online. Could you please share the dataset through Google Drive or another more accessible cloud? Thank you in advance.

**Comment by WanquanF** [comment]
I'll upload it to google drive soon

**Comment by UsamaHasan** [comment]
Any updates @WanquanF

**Comment by Aryan-Satpathy** [comment]
Dear authors,
Thank you for this excellent work. I was wondering if there was any update with the google drive. @WanquanF
