### ISSUE TITLE
install setup.py with error: command 'N:\\Microsoft Visual Stdio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe' failed with exit status 1120

### ISSUE THREAD

**Issue by freezeailis** [WanquanF/NeuralPoints#3]
thanks for ur work.

python setup.py install 
meet error as follow, how i slove it

(NePs) E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2>python setup.py install
running install
running bdist_egg
running egg_info
writing pointnet2.egg-info\PKG-INFO
writing dependency_links to pointnet2.egg-info\dependency_links.txt
writing top-level names to pointnet2.egg-info\top_level.txt
reading manifest file 'pointnet2.egg-info\SOURCES.txt'
writing manifest file 'pointnet2.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'pointnet2_cuda' extension
Emitting ninja build file E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
N:\Microsoft Visual Stdio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\anaconda3
\envs\NePs\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib/x64" /LIBPATH:D:\anaconda3\envs\NePs\libs /LIBPATH:D:\anaconda3\envs\NePs\P
Cbuild\amd64 "/LIBPATH:N:\Microsoft Visual Stdio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:N:\Microsoft Visual Stdio\2019\Community\VC\Tools\MSVC\14.29.30133\li
b\x64" "/LIBPATH:N:\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:N:\Windows Kits\10\lib\10.0.18362.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda
.lib torch_cuda.lib /EXPORT:PyInit_pointnet2_cuda E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src/pointnet2_api.obj E:\A\论文\codes\Neura
lPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src/ball_query.obj E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src
/ball_query_gpu.obj E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src/group_points.obj E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\poi
ntnet2\build\temp.win-amd64-3.8\Release\src/group_points_gpu.obj E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src/interpolate.obj E:\A\论
文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src/interpolate_gpu.obj E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-am
d64-3.8\Release\src/sampling.obj E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src/sampling_gpu.obj /OUT:build\lib.win-amd64-3.8\pointnet2_
cuda.cp38-win_amd64.pyd /IMPLIB:E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src\pointnet2_cuda.cp38-win_amd64.lib
  正在创建库 E:\A\论文\codes\NeuralPoints-main\model\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src\pointnet2_cuda.cp38-win_amd64.lib 和对象 E:\A\论文\codes\NeuralPoints-main\m
odel\conpu_v6\pointnet2\build\temp.win-amd64-3.8\Release\src\pointnet2_cuda.cp38-win_amd64.exp
ball_query_gpu.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) void __cdecl c10::detail::torchCheckFail(char const *,char const *,unsigned int,class std::basic_string<cha
r,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?torchCheckFail@detail@c10@@YAXPEBD0IAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
group_points_gpu.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) void __cdecl c10::detail::torchCheckFail(char const *,char const *,unsigned int,class std::basic_string<c
har,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?torchCheckFail@detail@c10@@YAXPEBD0IAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)

interpolate_gpu.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) void __cdecl c10::detail::torchCheckFail(char const *,char const *,unsigned int,class std::basic_string<ch
ar,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?torchCheckFail@detail@c10@@YAXPEBD0IAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
sampling_gpu.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) void __cdecl c10::detail::torchCheckFail(char const *,char const *,unsigned int,class std::basic_string<char,
struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?torchCheckFail@detail@c10@@YAXPEBD0IAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
ball_query_gpu.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) private: void __cdecl c10::IValue::destroy(void)" (__imp_?destroy@IValue@c10@@AEAAXXZ)
group_points_gpu.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) private: void __cdecl c10::IValue::destroy(void)" (__imp_?destroy@IValue@c10@@AEAAXXZ)
interpolate_gpu.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) private: void __cdecl c10::IValue::destroy(void)" (__imp_?destroy@IValue@c10@@AEAAXXZ)
sampling_gpu.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) private: void __cdecl c10::IValue::destroy(void)" (__imp_?destroy@IValue@c10@@AEAAXXZ)
build\lib.win-amd64-3.8\pointnet2_cuda.cp38-win_amd64.pyd : fatal error LNK1120: 2 个无法解析的外部命令
error: command 'N:\\Microsoft Visual Stdio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe' failed with exit status 1120

**Comment by WanquanF** [comment]
It seems that you are trying to run the code on Windows. You can test the code in a Linux environment.
