### ISSUE TITLE
测试的数据格式是什么样的？

### ISSUE THREAD

**Issue by XianheJiao** [WanquanF/NeuralPoints#6]
作者您好，请问一下测试的数据格式是什么样子的，在文件目录中我应该如何调用这些数据呢？比如说我想使用这个程序做一些自己的数据的上采样的话，应该怎么设置呢？希望得到您的回答，谢谢您了。

**Comment by WanquanF** [comment]
关于测试数据的格式：格式其实不太重要，我是因为个人习惯所以打包成了bin文件，就是以test开头的那个bin文件，你可以用任何格式存储和读取的。读进去之后是成为tensor的形式，注意tensor的size和代码中保持一致即可了
