### ISSUE TITLE
No module named 'torch_scatter'

### ISSUE THREAD

**Issue by fy5i5** [WanquanF/NeuralPoints#7]
运行train_script101_test.py 显示如标题  缺少No module named 'torch_scatter' 
执行pip install torch-scatter -f https://data.pyg.org/whl/torch-1.6.0+cu102.html 安装 
报错ERROR: Command errored out with exit status 1: /home/user/.conda/envs/fangyi-NePs/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ji2hjvud/torch-scatter_fe58236068334dc78028c5f89329631e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ji2hjvud/torch-scatter_fe58236068334dc78028c5f89329631e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rviv8pvl/install-record.txt --single-version-externally-managed --compile --install-headers /home/fangyi/.conda/envs/fangyi-NePs/include/python3.8/torch-scatter Check the logs for full command output.  
如何解决？

**Comment by WanquanF** [comment]
函数库安装失败的话，可以搜索其他的方式来安装torch-scatter吧，或者像报错提醒的“Check the logs for full command output.”

**Comment by fy5i5** [comment]
已经跑完测试集的测试结果train_script101_test.py  生成的各个部位的sample文件夹  想问问要怎么把各个部分点云拼接起来成完整的模型  谢谢您的回答

**Comment by WanquanF** [comment]
就把每一小块按照相应的刚性变换放到整体的点云中即可

**Comment by 2EternalDawn** [comment]
> 

请问您解决这个问题了吗？方便教我一下吗？应该如何做刚性变换呢？
